FROM python:3.9.7   

COPY vaccines /app

WORKDIR /app

RUN pip install -r requirements-m1.txt


ENV GOOGLE_APPLICATION_CREDENTIALS=sonic-ivy-388314-3f3e34d10699.json

EXPOSE 5000

ENTRYPOINT ["dagit", "-h", "0.0.0.0", "-p", "5000"]